name: reimburse_venturo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6                    # State management & routing
  google_fonts: ^6.1.0           # Inter font family
  table_calendar: ^3.0.9         # Calendar widget
  image_picker: ^1.0.7           # Image selection
  file_picker: ^6.1.1            # File selection (PDF, Excel, etc)
  intl: ^0.19.0                  # Currency & date formatting
  dotted_border: ^2.1.0          # Dotted border for upload area

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
